[package]
name = "i18n"
description = "Framework for internationalization"
version = "0.1.0"
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2021"
repository = "https://github.com/shipsimfan/lib-fluent"
license = "GPL-3.0-or-later"
publish = false

[features]
default = ["current"]

alloc = []
std = ["alloc"]
current = ["std"]
