[package]
name = "i18n-fluent"
description = ""

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[features]
std = []
